[package]
name = "leekscript-lsp"
version = "0.1.0"
edition = "2021"
description = "Language server for LeekScript (LSP)"
readme = "README.md"
license = "MIT"
repository = "https://github.com/NyalephTheCat/leekscript-lsp"
keywords = ["leekscript", "lsp", "language-server", "leek-wars"]
categories = ["development-tools", "parser-implementations"]

[lib]
name = "leekscript_lsp"
path = "src/lib.rs"

[[bin]]
name = "leekscript-lsp"
path = "src/main.rs"

[dependencies]
leekscript = { path = "../leekscript", features = ["utf16"] }
lsp-types = "0.94"
parking_lot = "0.12"
serde_json = "1"
sipha = { path = "../../sipha/sipha", default-features = false, features = ["std", "utf16"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "io-std"] }
tower-lsp = "0.20"

[dev-dependencies]
lsp-types = "0.94"
