[package]
name = "leekscript-lsp"
version = "0.1.0"
edition = "2021"
description = "Language server for LeekScript (LSP)"
readme = "README.md"
license = "MIT"
repository = "https://github.com/leek-wars/leekscript-lsp"
homepage = "https://github.com/leek-wars/leekscript-lsp"
documentation = "https://docs.rs/leekscript-lsp"
keywords = ["leekscript", "lsp", "language-server", "leek-wars"]
categories = ["development-tools", "parser-implementations"]

[lib]
name = "leekscript_lsp"
path = "src/lib.rs"

[[bin]]
name = "leekscript-lsp"
path = "src/main.rs"

[dependencies]
leekscript-rs = { version = "0.1", features = ["utf16", "lsp"] }
parking_lot = "0.12"
sipha = { version = "2.0.0", features = ["utf16"] }
tower-lsp = "0.20"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
